---
title: "MedicareAdvantage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
getwd()
#source(paste(path.code, "/_BuildFinalData.R", sep = ""), local = TRUE, echo = FALSE)
#source('1_Plan_Data.R')
source("~/ECON 470/Medicare-Advantage/R_code/paths.R")

source("1_Plan_Data.R",local=TRUE,echo=FALSE)
source(paste(path.code,"/2_Plan_Characteristics.R",sep=""),local=TRUE,echo=FALSE)
source(paste(path.code,"/3_Service_Areas.R",sep=""),local=TRUE,echo=FALSE)
source(paste(path.code,"/4_Penetration_Files.R",sep=""),local=TRUE,echo=FALSE)
source(paste(path.code,"/5_Star_Ratings.R",sep=""),local=TRUE,echo=FALSE)
source(paste(path.code,"/6_Risk_Rebates.R",sep=""),local=TRUE,echo=FALSE)
source(paste(path.code,"/7_MA_Benchmark.R",sep=""),local=TRUE,echo=FALSE)
source(paste(path.code,"/8_FFS_Costs.R",sep=""),local=TRUE,echo=FALSE)

#source("_BuildFinalData.R")
#source('1_Plan_Data.R')
#source(paste(path.code,"/_BuildFinalData.R",sep=""),local=TRUE,echo=FALSE)
source(paste("~/ECON 470/Medicare-Advantage/R_code/_BuildFinalData.R",sep=""),local=TRUE,echo=FALSE)
```

```{r cars}
full.ma.data %>% group_by(fips, year) %>% select(fips, year) %>% summarize(plan_count=n())
 ggplot(aes(x=as.factor(year),y=plan_count)) +
 stat_summary(fun.y="mean", geom="bar") +
 labs(
 x="Year",
 y="Number of Plans",
 title="Average Number of Plans per County"
 ) + scale_y_continuous(labels=comma) +
 theme_bw()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
